### ISSUE TITLE
Error When Adding Clusters to Heatmap

### ISSUE THREAD

**Issue by osmanmerdan** [XiaoLuo-boy/ggheatmap#12]
Hi, 
Adding clusters to rows or columns causes an error in ggheatmap. While running the first example code shared under the **Usage** title, I got the below error. 

_Error Message_ : Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In zero_range(as.numeric(limits)) : NAs introduced by coercion 

_Note_ : All the packages installed are recently updated.

Thank for your help. 
Sincerely.

**Comment by darjang09** [comment]
Hi, 

I´m getting a similar error when using `cluster_rows = T ,cluster_cols = T`.

```
Registered S3 method overwritten by 'dendextend':
  method     from 
  rev.hclust vegan
Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
i The deprecated feature was likely used in the factoextra package.
  Please report the issue at <https://github.com/kassambara/factoextra/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
2: In zero_range(as.numeric(limits)) : NAs introduced by coercion
```

It seems to be an error with some associated packages being updated for newer R version. 

Would be happy to hear if someone found a solution to make it work!

Best, D

**Comment by XiaoLuo-boy** [comment]
Thank you for trying out my ggheatmap R package. I'm sorry for any inconvenience caused by the error. The error is due to my package being outdated. In the past year, I had to prepared for the postgraduate entrance examination, so I didn't find this problem in time.
And now, I have updated ggheatmap in Github, and you can solve this problem by running the follow script:
devtools::install_github("XiaoLuo-boy/ggheatmap").

**Comment by osmanmerdan** [comment]
Thank you very much for the support. Good luck with your future career!

**Comment by waybo-zz** [comment]
Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed

---------------------
R 4.13
