### ISSUE TITLE
Increasing the cell size on plot

### ISSUE THREAD

**Issue by omrctnr** [XiaoLuo-boy/ggheatmap#9]
Hello, 

I try to create a plot using `ggheatmap()` and need to increase the cell size on the plot. Normally, while I am using `phheatmap()`, It has `cellwidht`, `cellheight` arguments also heatmap.2() contains the `width` and `height` argument.

Is there any argument that I can use with `ggheathmap()`

**Comment by XiaoLuo-boy** [comment]
@omrctnr 

I am sorry that the ggheatmap does not have arguments to meet your requirements.  I think, ` Complexheatmap ` maybe a good choice for you.

**Comment by omrctnr** [comment]
@XiaoLuo-boy 

Thank you for your response. As you suggested, the `Complexheatmap` was really what I want.
